---
title: "TimeSeries_MA"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LIBRARY


```{r}
library(ggplot2)
library(ggfortify)
```

## Including Plots

You can also embed plots, for example:

```{r}
# Generate noise
noise <- rnorm(10000)
noise[1:10]
```

```{r}
# Introduce a variable
ma_2=NULL

# Loop for generating MA(2) process

for(i in 3:10000){
    ma_2[i] <- noise[i]+0.7*noise[i-1]+0.2*noise[i-2]
}

ma_2[1:20]
```

```{r}
# Shift data to left by 2 units
moving_average_process <- ma_2[3:10000]

# Put time series structure on a vanilla data
moving_average_process <- ts(moving_average_process)
```

```{r}
# Partition output graphics as a multi frame of 2 rows and 1 column
par(mfrow=c(2,1))
# plot the process and plot its ACF
plot(moving_average_process, main='A moving average process of order 2', ylab=' ', col='blue')
acf(moving_average_process, main='Correlogram of a moving average process of order 2')

```

```{r}
x <- seq(1, length(moving_average_process), 1)
ma.df <- data.frame(x, moving_average_process)
ggplot(ma.df, aes(x = x, y = moving_average_process)) + geom_point()
```




```{r}
autoplot(moving_average_process)
```



```{r}

```

